# paths
workspace_path: "results"
dest_path: "destination"
path_list_study_one: "data/interval_path_list.txt"
path_list_study_two: "data/chris_path_list.txt"
template_profile: "data/template_profile.txt"
exclude_file: "data/exclude.txt"

params:
  standardize_sumstats:
    input_format: "metal_het"
    config_file: "config/config_metal_heterogeneity.yml"
